theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending"]

[keys.normal]
"P" = "paste_after"
"p" = "paste_before"
"minus" = ":sh time make -j4"
"=" = ":sh explorer.exe ."
"_" = ":toggle lsp.display-inlay-hints"
"+" = ":sh cargo r -q"

[keys.normal." "]
"P" = "paste_clipboard_after"
"p" = "paste_clipboard_before"
